### PR TITLE
Updates to sessions dates and date range calculations

### PR DESCRIPTION
**Pull request by mark-walle**
Changes from co-dev session with Hugo resulting from GDXDSD-1209.

### CODE REVIEW

**Comment by mark-walle** [comment]
The commits here change operators on is_in_range, last_period and current_period due to adding date_start and date_end dimensions which provide correct timezones before the comparisons. Cleaned up comments from previous commit and formatted file in looker to tidy.
@danpollock please review.

**Comment by danpollock** [comment]
@mark-walle : Looks good. 

I haven't had a chance to do much testing on it yet. Is it safe to assume we've done the testing?

**Comment by mark-walle** [comment]
@danpollock I'm seeing some problems with this in testing now that I hadn't noticed in my co-dev last Monday. I will cancel this PR.
For instance:
```
 # current period identifies sessions falling between the start and end of the date range selected
  dimension: current_period {
    group_label: "Flexible Filter"
    type: yesno
    sql: ${session_start_date} >= ${date_start} -- inclusive of the start date
      AND ${session_start_date} <= ${date_end}  -- also inclusive, since date range filters are already "until (before)"
      ;;
  }
```
is resulting in the _end date_ that's selected as part of a date range being included in the current_date.

**Comment by danpollock** [comment]
Sure. 

You can also leave the PR open and do fixes within the PR on subsequent commits if you like.

**Comment by mark-walle** [comment]
@a-ell and I reviewed this and we noticed that tests appear to be correct when we use `session_start_time` instead of `session_start_date` in the flexible filter dimensions. This actually corresponds closer to your `cfms_poc` model where you use `welcome_time`. Our thoughts are that the `_date` timeframe on `session_start` is truncating time (see reference) _before_ converting the timezone, having an unexpected effect where some that occurred within pdt-utc delta being regarded by these comparisons as if they are on a wrong date. When we use `_time`, which does not truncate the time, the timezone conversion occurs and the pdt-utc delta resolves correctly.

_[This explore](https://analytics.gov.bc.ca/explore/snowplow_web_block/sessions?toggle=fil&qid=w0IkB9AddqRUsQyiLITrNl)_ shows that where sessions date range is in range from 2018-10-03 until (before) 2018-10-05, the start times tagged with previous_period are those between 2018-10-01 00:00:00 and 2018-10-02 23:59:59, while those tagged with current_period are between 2018-10-03 00:00:00 and 2018-10-04 23:59:59, _as expected_.

_[This explore](https://analytics.gov.bc.ca/explore/snowplow_web_block/sessions?toggle=fil&qid=kINFGPTnLc4yiLPzxQfHEm)_ is the same ranges, but supressing the _time view, and showing session counts; just a less granular explore to show the expected output.

reference: https://docs.looker.com/reference/field-params/dimension_group

**Pull request merged**
